"""Add core SAVE-US entities

Revision ID: a43ca6faabcd
Revises: ef9812004064
Create Date: 2026-07-19 16:39:00.714531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a43ca6faabcd'
down_revision = 'ef9812004064'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('role', sa.Enum('CITIZEN', 'REPORTER', 'HOSPITAL_REPRESENTATIVE', 'MODERATOR', 'ADMINISTRATOR', name='userrole', native_enum=False, length=32), nullable=False),
    sa.Column('is_phone_verified', sa.Boolean(), nullable=False),
    sa.Column('country', sa.String(length=80), nullable=False),
    sa.Column('primary_region', sa.String(length=120), nullable=False),
    sa.Column('contribution_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_phone_number'), ['phone_number'], unique=True)

    op.create_table('alert_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('enabled_categories', sa.JSON(), nullable=False),
    sa.Column('followed_regions', sa.JSON(), nullable=False),
    sa.Column('email_notifications_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('alerts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('alert_type', sa.Enum('MISSING_PERSON', 'SUSPECTED_ABDUCTION', 'UNKNOWN_HOSPITAL_PATIENT', 'ROAD_ACCIDENT', name='alerttype', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'AI_REVIEW', 'NEEDS_MODERATION', 'PUBLISHED', 'REJECTED', 'REPORTED_FOUND', 'WITHDRAWN', 'EXPIRED', name='alertstatus', native_enum=False, length=32), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('public_summary', sa.Text(), nullable=True),
    sa.Column('country', sa.String(length=80), nullable=False),
    sa.Column('region', sa.String(length=120), nullable=True),
    sa.Column('approximate_zone', sa.String(length=180), nullable=True),
    sa.Column('reporter_id', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_alert_type'), ['alert_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_country'), ['country'], unique=False)
        batch_op.create_index('ix_alerts_country_region_status', ['country', 'region', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_region'), ['region'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_reporter_id'), ['reporter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_status'), ['status'], unique=False)
        batch_op.create_index('ix_alerts_type_status', ['alert_type', 'status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index('ix_alerts_type_status')
        batch_op.drop_index(batch_op.f('ix_alerts_status'))
        batch_op.drop_index(batch_op.f('ix_alerts_reporter_id'))
        batch_op.drop_index(batch_op.f('ix_alerts_region'))
        batch_op.drop_index(batch_op.f('ix_alerts_expires_at'))
        batch_op.drop_index('ix_alerts_country_region_status')
        batch_op.drop_index(batch_op.f('ix_alerts_country'))
        batch_op.drop_index(batch_op.f('ix_alerts_alert_type'))

    op.drop_table('alerts')
    op.drop_table('alert_preferences')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_phone_number'))

    op.drop_table('users')
    # ### end Alembic commands ###
